#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 12
#define STATE_COUNT 100
#define LARGE_STATE_COUNT 8
#define SYMBOL_COUNT 37
#define ALIAS_COUNT 2
#define TOKEN_COUNT 21
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 11
#define MAX_ALIAS_SEQUENCE_LENGTH 6

enum {
  sym_identifier = 1,
  anon_sym_LF = 2,
  anon_sym_LPAREN = 3,
  anon_sym_RPAREN = 4,
  aux_sym_infix_ex_token1 = 5,
  aux_sym_infix_ex_token2 = 6,
  aux_sym_infix_ex_token3 = 7,
  anon_sym_DASH = 8,
  anon_sym_EQ = 9,
  anon_sym_let = 10,
  anon_sym_in = 11,
  anon_sym_COMMA = 12,
  anon_sym_BSLASH = 13,
  anon_sym_DASH_GT = 14,
  anon_sym_if = 15,
  anon_sym_then = 16,
  anon_sym_else = 17,
  sym_const_int = 18,
  anon_sym_True = 19,
  anon_sym_False = 20,
  sym_unit = 21,
  sym__expression = 22,
  sym_infix_ex = 23,
  sym_prefix_ex = 24,
  sym_binding = 25,
  sym_let = 26,
  sym__binding_list = 27,
  sym_lambda = 28,
  sym_ap = 29,
  sym__param_list = 30,
  sym_cond = 31,
  sym_const_bool = 32,
  aux_sym_unit_repeat1 = 33,
  aux_sym_binding_repeat1 = 34,
  aux_sym__binding_list_repeat1 = 35,
  aux_sym__param_list_repeat1 = 36,
  alias_sym_infix_op = 37,
  alias_sym_prefix_op = 38,
};

static const char *ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_LF] = "\n",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [aux_sym_infix_ex_token1] = "infix_ex_token1",
  [aux_sym_infix_ex_token2] = "infix_ex_token2",
  [aux_sym_infix_ex_token3] = "infix_ex_token3",
  [anon_sym_DASH] = "-",
  [anon_sym_EQ] = "=",
  [anon_sym_let] = "let",
  [anon_sym_in] = "in",
  [anon_sym_COMMA] = ",",
  [anon_sym_BSLASH] = "\\",
  [anon_sym_DASH_GT] = "->",
  [anon_sym_if] = "if",
  [anon_sym_then] = "then",
  [anon_sym_else] = "else",
  [sym_const_int] = "const_int",
  [anon_sym_True] = "True",
  [anon_sym_False] = "False",
  [sym_unit] = "unit",
  [sym__expression] = "_expression",
  [sym_infix_ex] = "infix_ex",
  [sym_prefix_ex] = "prefix_ex",
  [sym_binding] = "binding",
  [sym_let] = "let",
  [sym__binding_list] = "_binding_list",
  [sym_lambda] = "lambda",
  [sym_ap] = "ap",
  [sym__param_list] = "_param_list",
  [sym_cond] = "cond",
  [sym_const_bool] = "const_bool",
  [aux_sym_unit_repeat1] = "unit_repeat1",
  [aux_sym_binding_repeat1] = "binding_repeat1",
  [aux_sym__binding_list_repeat1] = "_binding_list_repeat1",
  [aux_sym__param_list_repeat1] = "_param_list_repeat1",
  [alias_sym_infix_op] = "infix_op",
  [alias_sym_prefix_op] = "prefix_op",
};

static TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_LF] = anon_sym_LF,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [aux_sym_infix_ex_token1] = aux_sym_infix_ex_token1,
  [aux_sym_infix_ex_token2] = aux_sym_infix_ex_token2,
  [aux_sym_infix_ex_token3] = aux_sym_infix_ex_token3,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_let] = anon_sym_let,
  [anon_sym_in] = anon_sym_in,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_BSLASH] = anon_sym_BSLASH,
  [anon_sym_DASH_GT] = anon_sym_DASH_GT,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_then] = anon_sym_then,
  [anon_sym_else] = anon_sym_else,
  [sym_const_int] = sym_const_int,
  [anon_sym_True] = anon_sym_True,
  [anon_sym_False] = anon_sym_False,
  [sym_unit] = sym_unit,
  [sym__expression] = sym__expression,
  [sym_infix_ex] = sym_infix_ex,
  [sym_prefix_ex] = sym_prefix_ex,
  [sym_binding] = sym_binding,
  [sym_let] = sym_let,
  [sym__binding_list] = sym__binding_list,
  [sym_lambda] = sym_lambda,
  [sym_ap] = sym_ap,
  [sym__param_list] = sym__param_list,
  [sym_cond] = sym_cond,
  [sym_const_bool] = sym_const_bool,
  [aux_sym_unit_repeat1] = aux_sym_unit_repeat1,
  [aux_sym_binding_repeat1] = aux_sym_binding_repeat1,
  [aux_sym__binding_list_repeat1] = aux_sym__binding_list_repeat1,
  [aux_sym__param_list_repeat1] = aux_sym__param_list_repeat1,
  [alias_sym_infix_op] = alias_sym_infix_op,
  [alias_sym_prefix_op] = alias_sym_prefix_op,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_infix_ex_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_infix_ex_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_infix_ex_token3] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_let] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_in] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_then] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_else] = {
    .visible = true,
    .named = false,
  },
  [sym_const_int] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_True] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_False] = {
    .visible = true,
    .named = false,
  },
  [sym_unit] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_infix_ex] = {
    .visible = true,
    .named = true,
  },
  [sym_prefix_ex] = {
    .visible = true,
    .named = true,
  },
  [sym_binding] = {
    .visible = true,
    .named = true,
  },
  [sym_let] = {
    .visible = true,
    .named = true,
  },
  [sym__binding_list] = {
    .visible = false,
    .named = true,
  },
  [sym_lambda] = {
    .visible = true,
    .named = true,
  },
  [sym_ap] = {
    .visible = true,
    .named = true,
  },
  [sym__param_list] = {
    .visible = false,
    .named = true,
  },
  [sym_cond] = {
    .visible = true,
    .named = true,
  },
  [sym_const_bool] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_unit_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_binding_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__binding_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__param_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_infix_op] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_prefix_op] = {
    .visible = true,
    .named = true,
  },
};

enum {
  field_arguments = 1,
  field_bindings = 2,
  field_body = 3,
  field_else = 4,
  field_lhs = 5,
  field_op = 6,
  field_params = 7,
  field_pred = 8,
  field_receiver = 9,
  field_rhs = 10,
  field_then = 11,
};

static const char *ts_field_names[] = {
  [0] = NULL,
  [field_arguments] = "arguments",
  [field_bindings] = "bindings",
  [field_body] = "body",
  [field_else] = "else",
  [field_lhs] = "lhs",
  [field_op] = "op",
  [field_params] = "params",
  [field_pred] = "pred",
  [field_receiver] = "receiver",
  [field_rhs] = "rhs",
  [field_then] = "then",
};

static const TSFieldMapSlice ts_field_map_slices[11] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 1},
  [3] = {.index = 3, .length = 2},
  [4] = {.index = 5, .length = 1},
  [5] = {.index = 6, .length = 3},
  [6] = {.index = 9, .length = 2},
  [7] = {.index = 11, .length = 2},
  [8] = {.index = 13, .length = 3},
  [9] = {.index = 16, .length = 2},
  [10] = {.index = 18, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_body, 1},
    {field_op, 0},
  [2] =
    {field_body, 2},
  [3] =
    {field_lhs, 0},
    {field_rhs, 2},
  [5] =
    {field_receiver, 0},
  [6] =
    {field_lhs, 0},
    {field_op, 1},
    {field_rhs, 2},
  [9] =
    {field_bindings, 1},
    {field_body, 3},
  [11] =
    {field_body, 3},
    {field_params, 1},
  [13] =
    {field_lhs, 0},
    {field_params, 1},
    {field_rhs, 3},
  [16] =
    {field_arguments, 2},
    {field_receiver, 0},
  [18] =
    {field_else, 5},
    {field_pred, 1},
    {field_then, 3},
};

static TSSymbol ts_alias_sequences[11][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [0] = alias_sym_prefix_op,
  },
  [5] = {
    [1] = alias_sym_infix_op,
  },
};

static uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(7);
      if (lookahead == '(') ADVANCE(9);
      if (lookahead == ')') ADVANCE(10);
      if (lookahead == '*' ||
          lookahead == '/') ADVANCE(11);
      if (lookahead == '+') ADVANCE(12);
      if (lookahead == ',') ADVANCE(19);
      if (lookahead == '-') ADVANCE(15);
      if (lookahead == '<') ADVANCE(14);
      if (lookahead == '=') ADVANCE(18);
      if (lookahead == '>') ADVANCE(14);
      if (lookahead == '\\') ADVANCE(20);
      if (lookahead == '_') ADVANCE(4);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(22);
      END_STATE();
    case 1:
      if (lookahead == '(') ADVANCE(9);
      if (lookahead == ')') ADVANCE(10);
      if (lookahead == '*' ||
          lookahead == '/') ADVANCE(11);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(12);
      if (lookahead == ',') ADVANCE(19);
      if (lookahead == '<') ADVANCE(14);
      if (lookahead == '=') ADVANCE(18);
      if (lookahead == '>') ADVANCE(14);
      if (lookahead == '_') ADVANCE(4);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(1)
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(22);
      END_STATE();
    case 2:
      if (lookahead == '-') ADVANCE(3);
      if (lookahead == '=') ADVANCE(17);
      if (lookahead == '_') ADVANCE(4);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(2)
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(22);
      END_STATE();
    case 3:
      if (lookahead == '>') ADVANCE(21);
      END_STATE();
    case 4:
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(22);
      END_STATE();
    case 5:
      if (eof) ADVANCE(7);
      if (lookahead == '\n') ADVANCE(8);
      if (lookahead == '(') ADVANCE(9);
      if (lookahead == '*' ||
          lookahead == '/') ADVANCE(11);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(12);
      if (lookahead == '<') ADVANCE(14);
      if (lookahead == '=') ADVANCE(18);
      if (lookahead == '>') ADVANCE(14);
      if (lookahead == '_') ADVANCE(4);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(5)
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(22);
      END_STATE();
    case 6:
      if (eof) ADVANCE(7);
      if (lookahead == '(') ADVANCE(9);
      if (lookahead == ')') ADVANCE(10);
      if (lookahead == '-') ADVANCE(16);
      if (lookahead == '\\') ADVANCE(20);
      if (lookahead == '_') ADVANCE(4);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(6)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(23);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(22);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_LF);
      if (lookahead == '\n') ADVANCE(8);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(aux_sym_infix_ex_token1);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(aux_sym_infix_ex_token2);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(aux_sym_infix_ex_token3);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(aux_sym_infix_ex_token3);
      if (lookahead == '=') ADVANCE(13);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_DASH);
      if (lookahead == '>') ADVANCE(21);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_DASH);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(23);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '=') ADVANCE(13);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_BSLASH);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_DASH_GT);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '\'' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(22);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_const_int);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(23);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'F') ADVANCE(1);
      if (lookahead == 'T') ADVANCE(2);
      if (lookahead == 'e') ADVANCE(3);
      if (lookahead == 'i') ADVANCE(4);
      if (lookahead == 'l') ADVANCE(5);
      if (lookahead == 't') ADVANCE(6);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      END_STATE();
    case 1:
      if (lookahead == 'a') ADVANCE(7);
      END_STATE();
    case 2:
      if (lookahead == 'r') ADVANCE(8);
      END_STATE();
    case 3:
      if (lookahead == 'l') ADVANCE(9);
      END_STATE();
    case 4:
      if (lookahead == 'f') ADVANCE(10);
      if (lookahead == 'n') ADVANCE(11);
      END_STATE();
    case 5:
      if (lookahead == 'e') ADVANCE(12);
      END_STATE();
    case 6:
      if (lookahead == 'h') ADVANCE(13);
      END_STATE();
    case 7:
      if (lookahead == 'l') ADVANCE(14);
      END_STATE();
    case 8:
      if (lookahead == 'u') ADVANCE(15);
      END_STATE();
    case 9:
      if (lookahead == 's') ADVANCE(16);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_if);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_in);
      END_STATE();
    case 12:
      if (lookahead == 't') ADVANCE(17);
      END_STATE();
    case 13:
      if (lookahead == 'e') ADVANCE(18);
      END_STATE();
    case 14:
      if (lookahead == 's') ADVANCE(19);
      END_STATE();
    case 15:
      if (lookahead == 'e') ADVANCE(20);
      END_STATE();
    case 16:
      if (lookahead == 'e') ADVANCE(21);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_let);
      END_STATE();
    case 18:
      if (lookahead == 'n') ADVANCE(22);
      END_STATE();
    case 19:
      if (lookahead == 'e') ADVANCE(23);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_True);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_else);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_then);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_False);
      END_STATE();
    default:
      return false;
  }
}

static TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 6},
  [2] = {.lex_state = 6},
  [3] = {.lex_state = 6},
  [4] = {.lex_state = 6},
  [5] = {.lex_state = 6},
  [6] = {.lex_state = 6},
  [7] = {.lex_state = 6},
  [8] = {.lex_state = 6},
  [9] = {.lex_state = 6},
  [10] = {.lex_state = 6},
  [11] = {.lex_state = 6},
  [12] = {.lex_state = 6},
  [13] = {.lex_state = 6},
  [14] = {.lex_state = 6},
  [15] = {.lex_state = 6},
  [16] = {.lex_state = 6},
  [17] = {.lex_state = 6},
  [18] = {.lex_state = 6},
  [19] = {.lex_state = 6},
  [20] = {.lex_state = 6},
  [21] = {.lex_state = 6},
  [22] = {.lex_state = 6},
  [23] = {.lex_state = 6},
  [24] = {.lex_state = 6},
  [25] = {.lex_state = 6},
  [26] = {.lex_state = 6},
  [27] = {.lex_state = 6},
  [28] = {.lex_state = 6},
  [29] = {.lex_state = 6},
  [30] = {.lex_state = 6},
  [31] = {.lex_state = 6},
  [32] = {.lex_state = 6},
  [33] = {.lex_state = 6},
  [34] = {.lex_state = 6},
  [35] = {.lex_state = 6},
  [36] = {.lex_state = 1},
  [37] = {.lex_state = 1},
  [38] = {.lex_state = 1},
  [39] = {.lex_state = 1},
  [40] = {.lex_state = 1},
  [41] = {.lex_state = 1},
  [42] = {.lex_state = 1},
  [43] = {.lex_state = 1},
  [44] = {.lex_state = 5},
  [45] = {.lex_state = 1},
  [46] = {.lex_state = 1},
  [47] = {.lex_state = 1},
  [48] = {.lex_state = 1},
  [49] = {.lex_state = 1},
  [50] = {.lex_state = 1},
  [51] = {.lex_state = 1},
  [52] = {.lex_state = 1},
  [53] = {.lex_state = 5},
  [54] = {.lex_state = 5},
  [55] = {.lex_state = 5},
  [56] = {.lex_state = 5},
  [57] = {.lex_state = 1},
  [58] = {.lex_state = 5},
  [59] = {.lex_state = 5},
  [60] = {.lex_state = 5},
  [61] = {.lex_state = 5},
  [62] = {.lex_state = 5},
  [63] = {.lex_state = 5},
  [64] = {.lex_state = 5},
  [65] = {.lex_state = 5},
  [66] = {.lex_state = 5},
  [67] = {.lex_state = 5},
  [68] = {.lex_state = 5},
  [69] = {.lex_state = 5},
  [70] = {.lex_state = 1},
  [71] = {.lex_state = 1},
  [72] = {.lex_state = 1},
  [73] = {.lex_state = 1},
  [74] = {.lex_state = 1},
  [75] = {.lex_state = 1},
  [76] = {.lex_state = 2},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 2},
  [82] = {.lex_state = 2},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 5},
  [85] = {.lex_state = 5},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 2},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 2},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
};

static uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [aux_sym_infix_ex_token1] = ACTIONS(1),
    [aux_sym_infix_ex_token2] = ACTIONS(1),
    [aux_sym_infix_ex_token3] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_let] = ACTIONS(1),
    [anon_sym_in] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_BSLASH] = ACTIONS(1),
    [anon_sym_DASH_GT] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_then] = ACTIONS(1),
    [anon_sym_else] = ACTIONS(1),
    [anon_sym_True] = ACTIONS(1),
    [anon_sym_False] = ACTIONS(1),
  },
  [1] = {
    [sym_unit] = STATE(96),
    [sym__expression] = STATE(53),
    [sym_infix_ex] = STATE(53),
    [sym_prefix_ex] = STATE(53),
    [sym_binding] = STATE(53),
    [sym_let] = STATE(53),
    [sym_lambda] = STATE(53),
    [sym_ap] = STATE(53),
    [sym_cond] = STATE(53),
    [sym_const_bool] = STATE(53),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_identifier] = ACTIONS(5),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_DASH] = ACTIONS(9),
    [anon_sym_let] = ACTIONS(11),
    [anon_sym_BSLASH] = ACTIONS(13),
    [anon_sym_if] = ACTIONS(15),
    [sym_const_int] = ACTIONS(17),
    [anon_sym_True] = ACTIONS(19),
    [anon_sym_False] = ACTIONS(19),
  },
  [2] = {
    [sym__expression] = STATE(52),
    [sym_infix_ex] = STATE(52),
    [sym_prefix_ex] = STATE(52),
    [sym_binding] = STATE(52),
    [sym_let] = STATE(52),
    [sym_lambda] = STATE(52),
    [sym_ap] = STATE(52),
    [sym__param_list] = STATE(95),
    [sym_cond] = STATE(52),
    [sym_const_bool] = STATE(52),
    [sym_identifier] = ACTIONS(21),
    [anon_sym_LPAREN] = ACTIONS(23),
    [anon_sym_RPAREN] = ACTIONS(25),
    [anon_sym_DASH] = ACTIONS(27),
    [anon_sym_let] = ACTIONS(29),
    [anon_sym_BSLASH] = ACTIONS(31),
    [anon_sym_if] = ACTIONS(33),
    [sym_const_int] = ACTIONS(35),
    [anon_sym_True] = ACTIONS(37),
    [anon_sym_False] = ACTIONS(37),
  },
  [3] = {
    [sym__expression] = STATE(52),
    [sym_infix_ex] = STATE(52),
    [sym_prefix_ex] = STATE(52),
    [sym_binding] = STATE(52),
    [sym_let] = STATE(52),
    [sym_lambda] = STATE(52),
    [sym_ap] = STATE(52),
    [sym__param_list] = STATE(99),
    [sym_cond] = STATE(52),
    [sym_const_bool] = STATE(52),
    [sym_identifier] = ACTIONS(21),
    [anon_sym_LPAREN] = ACTIONS(23),
    [anon_sym_RPAREN] = ACTIONS(39),
    [anon_sym_DASH] = ACTIONS(27),
    [anon_sym_let] = ACTIONS(29),
    [anon_sym_BSLASH] = ACTIONS(31),
    [anon_sym_if] = ACTIONS(33),
    [sym_const_int] = ACTIONS(35),
    [anon_sym_True] = ACTIONS(37),
    [anon_sym_False] = ACTIONS(37),
  },
  [4] = {
    [sym__expression] = STATE(57),
    [sym_infix_ex] = STATE(57),
    [sym_prefix_ex] = STATE(57),
    [sym_binding] = STATE(57),
    [sym_let] = STATE(57),
    [sym_lambda] = STATE(57),
    [sym_ap] = STATE(57),
    [sym_cond] = STATE(57),
    [sym_const_bool] = STATE(57),
    [sym_identifier] = ACTIONS(21),
    [anon_sym_LPAREN] = ACTIONS(23),
    [anon_sym_RPAREN] = ACTIONS(41),
    [anon_sym_DASH] = ACTIONS(27),
    [anon_sym_let] = ACTIONS(29),
    [anon_sym_BSLASH] = ACTIONS(31),
    [anon_sym_if] = ACTIONS(33),
    [sym_const_int] = ACTIONS(43),
    [anon_sym_True] = ACTIONS(37),
    [anon_sym_False] = ACTIONS(37),
  },
  [5] = {
    [sym__expression] = STATE(57),
    [sym_infix_ex] = STATE(57),
    [sym_prefix_ex] = STATE(57),
    [sym_binding] = STATE(57),
    [sym_let] = STATE(57),
    [sym_lambda] = STATE(57),
    [sym_ap] = STATE(57),
    [sym_cond] = STATE(57),
    [sym_const_bool] = STATE(57),
    [sym_identifier] = ACTIONS(21),
    [anon_sym_LPAREN] = ACTIONS(23),
    [anon_sym_RPAREN] = ACTIONS(45),
    [anon_sym_DASH] = ACTIONS(27),
    [anon_sym_let] = ACTIONS(29),
    [anon_sym_BSLASH] = ACTIONS(31),
    [anon_sym_if] = ACTIONS(33),
    [sym_const_int] = ACTIONS(43),
    [anon_sym_True] = ACTIONS(37),
    [anon_sym_False] = ACTIONS(37),
  },
  [6] = {
    [sym__expression] = STATE(61),
    [sym_infix_ex] = STATE(61),
    [sym_prefix_ex] = STATE(61),
    [sym_binding] = STATE(61),
    [sym_let] = STATE(61),
    [sym_lambda] = STATE(61),
    [sym_ap] = STATE(61),
    [sym_cond] = STATE(61),
    [sym_const_bool] = STATE(61),
    [ts_builtin_sym_end] = ACTIONS(47),
    [sym_identifier] = ACTIONS(5),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_DASH] = ACTIONS(9),
    [anon_sym_let] = ACTIONS(11),
    [anon_sym_BSLASH] = ACTIONS(13),
    [anon_sym_if] = ACTIONS(15),
    [sym_const_int] = ACTIONS(49),
    [anon_sym_True] = ACTIONS(19),
    [anon_sym_False] = ACTIONS(19),
  },
  [7] = {
    [sym__expression] = STATE(61),
    [sym_infix_ex] = STATE(61),
    [sym_prefix_ex] = STATE(61),
    [sym_binding] = STATE(61),
    [sym_let] = STATE(61),
    [sym_lambda] = STATE(61),
    [sym_ap] = STATE(61),
    [sym_cond] = STATE(61),
    [sym_const_bool] = STATE(61),
    [ts_builtin_sym_end] = ACTIONS(51),
    [sym_identifier] = ACTIONS(5),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_DASH] = ACTIONS(9),
    [anon_sym_let] = ACTIONS(11),
    [anon_sym_BSLASH] = ACTIONS(13),
    [anon_sym_if] = ACTIONS(15),
    [sym_const_int] = ACTIONS(49),
    [anon_sym_True] = ACTIONS(19),
    [anon_sym_False] = ACTIONS(19),
  },
};

static uint16_t ts_small_parse_table[] = {
  [0] = 9,
    ACTIONS(21), 1,
      sym_identifier,
    ACTIONS(23), 1,
      anon_sym_LPAREN,
    ACTIONS(27), 1,
      anon_sym_DASH,
    ACTIONS(29), 1,
      anon_sym_let,
    ACTIONS(31), 1,
      anon_sym_BSLASH,
    ACTIONS(33), 1,
      anon_sym_if,
    ACTIONS(53), 1,
      sym_const_int,
    ACTIONS(37), 2,
      anon_sym_True,
      anon_sym_False,
    STATE(51), 9,
      sym__expression,
      sym_infix_ex,
      sym_prefix_ex,
      sym_binding,
      sym_let,
      sym_lambda,
      sym_ap,
      sym_cond,
      sym_const_bool,
  [37] = 9,
    ACTIONS(5), 1,
      sym_identifier,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_DASH,
    ACTIONS(11), 1,
      anon_sym_let,
    ACTIONS(13), 1,
      anon_sym_BSLASH,
    ACTIONS(15), 1,
      anon_sym_if,
    ACTIONS(55), 1,
      sym_const_int,
    ACTIONS(19), 2,
      anon_sym_True,
      anon_sym_False,
    STATE(69), 9,
      sym__expression,
      sym_infix_ex,
      sym_prefix_ex,
      sym_binding,
      sym_let,
      sym_lambda,
      sym_ap,
      sym_cond,
      sym_const_bool,
  [74] = 9,
    ACTIONS(21), 1,
      sym_identifier,
    ACTIONS(23), 1,
      anon_sym_LPAREN,
    ACTIONS(27), 1,
      anon_sym_DASH,
    ACTIONS(29), 1,
      anon_sym_let,
    ACTIONS(31), 1,
      anon_sym_BSLASH,
    ACTIONS(33), 1,
      anon_sym_if,
    ACTIONS(57), 1,
      sym_const_int,
    ACTIONS(37), 2,
      anon_sym_True,
      anon_sym_False,
    STATE(74), 9,
      sym__expression,
      sym_infix_ex,
      sym_prefix_ex,
      sym_binding,
      sym_let,
      sym_lambda,
      sym_ap,
      sym_cond,
      sym_const_bool,
  [111] = 9,
    ACTIONS(21), 1,
      sym_identifier,
    ACTIONS(23), 1,
      anon_sym_LPAREN,
    ACTIONS(27), 1,
      anon_sym_DASH,
    ACTIONS(29), 1,
      anon_sym_let,
    ACTIONS(31), 1,
      anon_sym_BSLASH,
    ACTIONS(33), 1,
      anon_sym_if,
    ACTIONS(59), 1,
      sym_const_int,
    ACTIONS(37), 2,
      anon_sym_True,
      anon_sym_False,
    STATE(47), 9,
      sym__expression,
      sym_infix_ex,
      sym_prefix_ex,
      sym_binding,
      sym_let,
      sym_lambda,
      sym_ap,
      sym_cond,
      sym_const_bool,
  [148] = 9,
    ACTIONS(21), 1,
      sym_identifier,
    ACTIONS(23), 1,
      anon_sym_LPAREN,
    ACTIONS(27), 1,
      anon_sym_DASH,
    ACTIONS(29), 1,
      anon_sym_let,
    ACTIONS(31), 1,
      anon_sym_BSLASH,
    ACTIONS(33), 1,
      anon_sym_if,
    ACTIONS(61), 1,
      sym_const_int,
    ACTIONS(37), 2,
      anon_sym_True,
      anon_sym_False,
    STATE(50), 9,
      sym__expression,
      sym_infix_ex,
      sym_prefix_ex,
      sym_binding,
      sym_let,
      sym_lambda,
      sym_ap,
      sym_cond,
      sym_const_bool,
  [185] = 9,
    ACTIONS(21), 1,
      sym_identifier,
    ACTIONS(23), 1,
      anon_sym_LPAREN,
    ACTIONS(27), 1,
      anon_sym_DASH,
    ACTIONS(29), 1,
      anon_sym_let,
    ACTIONS(31), 1,
      anon_sym_BSLASH,
    ACTIONS(33), 1,
      anon_sym_if,
    ACTIONS(63), 1,
      sym_const_int,
    ACTIONS(37), 2,
      anon_sym_True,
      anon_sym_False,
    STATE(43), 9,
      sym__expression,
      sym_infix_ex,
      sym_prefix_ex,
      sym_binding,
      sym_let,
      sym_lambda,
      sym_ap,
      sym_cond,
      sym_const_bool,
  [222] = 9,
    ACTIONS(21), 1,
      sym_identifier,
    ACTIONS(23), 1,
      anon_sym_LPAREN,
    ACTIONS(27), 1,
      anon_sym_DASH,
    ACTIONS(29), 1,
      anon_sym_let,
    ACTIONS(31), 1,
      anon_sym_BSLASH,
    ACTIONS(33), 1,
      anon_sym_if,
    ACTIONS(65), 1,
      sym_const_int,
    ACTIONS(37), 2,
      anon_sym_True,
      anon_sym_False,
    STATE(42), 9,
      sym__expression,
      sym_infix_ex,
      sym_prefix_ex,
      sym_binding,
      sym_let,
      sym_lambda,
      sym_ap,
      sym_cond,
      sym_const_bool,
  [259] = 9,
    ACTIONS(21), 1,
      sym_identifier,
    ACTIONS(23), 1,
      anon_sym_LPAREN,
    ACTIONS(27), 1,
      anon_sym_DASH,
    ACTIONS(29), 1,
      anon_sym_let,
    ACTIONS(31), 1,
      anon_sym_BSLASH,
    ACTIONS(33), 1,
      anon_sym_if,
    ACTIONS(67), 1,
      sym_const_int,
    ACTIONS(37), 2,
      anon_sym_True,
      anon_sym_False,
    STATE(46), 9,
      sym__expression,
      sym_infix_ex,
      sym_prefix_ex,
      sym_binding,
      sym_let,
      sym_lambda,
      sym_ap,
      sym_cond,
      sym_const_bool,
  [296] = 9,
    ACTIONS(21), 1,
      sym_identifier,
    ACTIONS(23), 1,
      anon_sym_LPAREN,
    ACTIONS(27), 1,
      anon_sym_DASH,
    ACTIONS(29), 1,
      anon_sym_let,
    ACTIONS(31), 1,
      anon_sym_BSLASH,
    ACTIONS(33), 1,
      anon_sym_if,
    ACTIONS(69), 1,
      sym_const_int,
    ACTIONS(37), 2,
      anon_sym_True,
      anon_sym_False,
    STATE(40), 9,
      sym__expression,
      sym_infix_ex,
      sym_prefix_ex,
      sym_binding,
      sym_let,
      sym_lambda,
      sym_ap,
      sym_cond,
      sym_const_bool,
  [333] = 9,
    ACTIONS(5), 1,
      sym_identifier,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_DASH,
    ACTIONS(11), 1,
      anon_sym_let,
    ACTIONS(13), 1,
      anon_sym_BSLASH,
    ACTIONS(15), 1,
      anon_sym_if,
    ACTIONS(71), 1,
      sym_const_int,
    ACTIONS(19), 2,
      anon_sym_True,
      anon_sym_False,
    STATE(58), 9,
      sym__expression,
      sym_infix_ex,
      sym_prefix_ex,
      sym_binding,
      sym_let,
      sym_lambda,
      sym_ap,
      sym_cond,
      sym_const_bool,
  [370] = 9,
    ACTIONS(21), 1,
      sym_identifier,
    ACTIONS(23), 1,
      anon_sym_LPAREN,
    ACTIONS(27), 1,
      anon_sym_DASH,
    ACTIONS(29), 1,
      anon_sym_let,
    ACTIONS(31), 1,
      anon_sym_BSLASH,
    ACTIONS(33), 1,
      anon_sym_if,
    ACTIONS(73), 1,
      sym_const_int,
    ACTIONS(37), 2,
      anon_sym_True,
      anon_sym_False,
    STATE(49), 9,
      sym__expression,
      sym_infix_ex,
      sym_prefix_ex,
      sym_binding,
      sym_let,
      sym_lambda,
      sym_ap,
      sym_cond,
      sym_const_bool,
  [407] = 9,
    ACTIONS(5), 1,
      sym_identifier,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_DASH,
    ACTIONS(11), 1,
      anon_sym_let,
    ACTIONS(13), 1,
      anon_sym_BSLASH,
    ACTIONS(15), 1,
      anon_sym_if,
    ACTIONS(75), 1,
      sym_const_int,
    ACTIONS(19), 2,
      anon_sym_True,
      anon_sym_False,
    STATE(55), 9,
      sym__expression,
      sym_infix_ex,
      sym_prefix_ex,
      sym_binding,
      sym_let,
      sym_lambda,
      sym_ap,
      sym_cond,
      sym_const_bool,
  [444] = 9,
    ACTIONS(21), 1,
      sym_identifier,
    ACTIONS(23), 1,
      anon_sym_LPAREN,
    ACTIONS(27), 1,
      anon_sym_DASH,
    ACTIONS(29), 1,
      anon_sym_let,
    ACTIONS(31), 1,
      anon_sym_BSLASH,
    ACTIONS(33), 1,
      anon_sym_if,
    ACTIONS(77), 1,
      sym_const_int,
    ACTIONS(37), 2,
      anon_sym_True,
      anon_sym_False,
    STATE(37), 9,
      sym__expression,
      sym_infix_ex,
      sym_prefix_ex,
      sym_binding,
      sym_let,
      sym_lambda,
      sym_ap,
      sym_cond,
      sym_const_bool,
  [481] = 9,
    ACTIONS(21), 1,
      sym_identifier,
    ACTIONS(23), 1,
      anon_sym_LPAREN,
    ACTIONS(27), 1,
      anon_sym_DASH,
    ACTIONS(29), 1,
      anon_sym_let,
    ACTIONS(31), 1,
      anon_sym_BSLASH,
    ACTIONS(33), 1,
      anon_sym_if,
    ACTIONS(79), 1,
      sym_const_int,
    ACTIONS(37), 2,
      anon_sym_True,
      anon_sym_False,
    STATE(71), 9,
      sym__expression,
      sym_infix_ex,
      sym_prefix_ex,
      sym_binding,
      sym_let,
      sym_lambda,
      sym_ap,
      sym_cond,
      sym_const_bool,
  [518] = 9,
    ACTIONS(21), 1,
      sym_identifier,
    ACTIONS(23), 1,
      anon_sym_LPAREN,
    ACTIONS(27), 1,
      anon_sym_DASH,
    ACTIONS(29), 1,
      anon_sym_let,
    ACTIONS(31), 1,
      anon_sym_BSLASH,
    ACTIONS(33), 1,
      anon_sym_if,
    ACTIONS(81), 1,
      sym_const_int,
    ACTIONS(37), 2,
      anon_sym_True,
      anon_sym_False,
    STATE(70), 9,
      sym__expression,
      sym_infix_ex,
      sym_prefix_ex,
      sym_binding,
      sym_let,
      sym_lambda,
      sym_ap,
      sym_cond,
      sym_const_bool,
  [555] = 9,
    ACTIONS(21), 1,
      sym_identifier,
    ACTIONS(23), 1,
      anon_sym_LPAREN,
    ACTIONS(27), 1,
      anon_sym_DASH,
    ACTIONS(29), 1,
      anon_sym_let,
    ACTIONS(31), 1,
      anon_sym_BSLASH,
    ACTIONS(33), 1,
      anon_sym_if,
    ACTIONS(83), 1,
      sym_const_int,
    ACTIONS(37), 2,
      anon_sym_True,
      anon_sym_False,
    STATE(72), 9,
      sym__expression,
      sym_infix_ex,
      sym_prefix_ex,
      sym_binding,
      sym_let,
      sym_lambda,
      sym_ap,
      sym_cond,
      sym_const_bool,
  [592] = 9,
    ACTIONS(5), 1,
      sym_identifier,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_DASH,
    ACTIONS(11), 1,
      anon_sym_let,
    ACTIONS(13), 1,
      anon_sym_BSLASH,
    ACTIONS(15), 1,
      anon_sym_if,
    ACTIONS(85), 1,
      sym_const_int,
    ACTIONS(19), 2,
      anon_sym_True,
      anon_sym_False,
    STATE(68), 9,
      sym__expression,
      sym_infix_ex,
      sym_prefix_ex,
      sym_binding,
      sym_let,
      sym_lambda,
      sym_ap,
      sym_cond,
      sym_const_bool,
  [629] = 9,
    ACTIONS(5), 1,
      sym_identifier,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_DASH,
    ACTIONS(11), 1,
      anon_sym_let,
    ACTIONS(13), 1,
      anon_sym_BSLASH,
    ACTIONS(15), 1,
      anon_sym_if,
    ACTIONS(87), 1,
      sym_const_int,
    ACTIONS(19), 2,
      anon_sym_True,
      anon_sym_False,
    STATE(67), 9,
      sym__expression,
      sym_infix_ex,
      sym_prefix_ex,
      sym_binding,
      sym_let,
      sym_lambda,
      sym_ap,
      sym_cond,
      sym_const_bool,
  [666] = 9,
    ACTIONS(21), 1,
      sym_identifier,
    ACTIONS(23), 1,
      anon_sym_LPAREN,
    ACTIONS(27), 1,
      anon_sym_DASH,
    ACTIONS(29), 1,
      anon_sym_let,
    ACTIONS(31), 1,
      anon_sym_BSLASH,
    ACTIONS(33), 1,
      anon_sym_if,
    ACTIONS(89), 1,
      sym_const_int,
    ACTIONS(37), 2,
      anon_sym_True,
      anon_sym_False,
    STATE(39), 9,
      sym__expression,
      sym_infix_ex,
      sym_prefix_ex,
      sym_binding,
      sym_let,
      sym_lambda,
      sym_ap,
      sym_cond,
      sym_const_bool,
  [703] = 9,
    ACTIONS(5), 1,
      sym_identifier,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_DASH,
    ACTIONS(11), 1,
      anon_sym_let,
    ACTIONS(13), 1,
      anon_sym_BSLASH,
    ACTIONS(15), 1,
      anon_sym_if,
    ACTIONS(91), 1,
      sym_const_int,
    ACTIONS(19), 2,
      anon_sym_True,
      anon_sym_False,
    STATE(62), 9,
      sym__expression,
      sym_infix_ex,
      sym_prefix_ex,
      sym_binding,
      sym_let,
      sym_lambda,
      sym_ap,
      sym_cond,
      sym_const_bool,
  [740] = 9,
    ACTIONS(21), 1,
      sym_identifier,
    ACTIONS(23), 1,
      anon_sym_LPAREN,
    ACTIONS(27), 1,
      anon_sym_DASH,
    ACTIONS(29), 1,
      anon_sym_let,
    ACTIONS(31), 1,
      anon_sym_BSLASH,
    ACTIONS(33), 1,
      anon_sym_if,
    ACTIONS(43), 1,
      sym_const_int,
    ACTIONS(37), 2,
      anon_sym_True,
      anon_sym_False,
    STATE(57), 9,
      sym__expression,
      sym_infix_ex,
      sym_prefix_ex,
      sym_binding,
      sym_let,
      sym_lambda,
      sym_ap,
      sym_cond,
      sym_const_bool,
  [777] = 9,
    ACTIONS(21), 1,
      sym_identifier,
    ACTIONS(23), 1,
      anon_sym_LPAREN,
    ACTIONS(27), 1,
      anon_sym_DASH,
    ACTIONS(29), 1,
      anon_sym_let,
    ACTIONS(31), 1,
      anon_sym_BSLASH,
    ACTIONS(33), 1,
      anon_sym_if,
    ACTIONS(93), 1,
      sym_const_int,
    ACTIONS(37), 2,
      anon_sym_True,
      anon_sym_False,
    STATE(73), 9,
      sym__expression,
      sym_infix_ex,
      sym_prefix_ex,
      sym_binding,
      sym_let,
      sym_lambda,
      sym_ap,
      sym_cond,
      sym_const_bool,
  [814] = 9,
    ACTIONS(5), 1,
      sym_identifier,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_DASH,
    ACTIONS(11), 1,
      anon_sym_let,
    ACTIONS(13), 1,
      anon_sym_BSLASH,
    ACTIONS(15), 1,
      anon_sym_if,
    ACTIONS(95), 1,
      sym_const_int,
    ACTIONS(19), 2,
      anon_sym_True,
      anon_sym_False,
    STATE(65), 9,
      sym__expression,
      sym_infix_ex,
      sym_prefix_ex,
      sym_binding,
      sym_let,
      sym_lambda,
      sym_ap,
      sym_cond,
      sym_const_bool,
  [851] = 9,
    ACTIONS(5), 1,
      sym_identifier,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_DASH,
    ACTIONS(11), 1,
      anon_sym_let,
    ACTIONS(13), 1,
      anon_sym_BSLASH,
    ACTIONS(15), 1,
      anon_sym_if,
    ACTIONS(97), 1,
      sym_const_int,
    ACTIONS(19), 2,
      anon_sym_True,
      anon_sym_False,
    STATE(60), 9,
      sym__expression,
      sym_infix_ex,
      sym_prefix_ex,
      sym_binding,
      sym_let,
      sym_lambda,
      sym_ap,
      sym_cond,
      sym_const_bool,
  [888] = 9,
    ACTIONS(5), 1,
      sym_identifier,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_DASH,
    ACTIONS(11), 1,
      anon_sym_let,
    ACTIONS(13), 1,
      anon_sym_BSLASH,
    ACTIONS(15), 1,
      anon_sym_if,
    ACTIONS(99), 1,
      sym_const_int,
    ACTIONS(19), 2,
      anon_sym_True,
      anon_sym_False,
    STATE(63), 9,
      sym__expression,
      sym_infix_ex,
      sym_prefix_ex,
      sym_binding,
      sym_let,
      sym_lambda,
      sym_ap,
      sym_cond,
      sym_const_bool,
  [925] = 9,
    ACTIONS(5), 1,
      sym_identifier,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_DASH,
    ACTIONS(11), 1,
      anon_sym_let,
    ACTIONS(13), 1,
      anon_sym_BSLASH,
    ACTIONS(15), 1,
      anon_sym_if,
    ACTIONS(49), 1,
      sym_const_int,
    ACTIONS(19), 2,
      anon_sym_True,
      anon_sym_False,
    STATE(61), 9,
      sym__expression,
      sym_infix_ex,
      sym_prefix_ex,
      sym_binding,
      sym_let,
      sym_lambda,
      sym_ap,
      sym_cond,
      sym_const_bool,
  [962] = 9,
    ACTIONS(21), 1,
      sym_identifier,
    ACTIONS(23), 1,
      anon_sym_LPAREN,
    ACTIONS(27), 1,
      anon_sym_DASH,
    ACTIONS(29), 1,
      anon_sym_let,
    ACTIONS(31), 1,
      anon_sym_BSLASH,
    ACTIONS(33), 1,
      anon_sym_if,
    ACTIONS(101), 1,
      sym_const_int,
    ACTIONS(37), 2,
      anon_sym_True,
      anon_sym_False,
    STATE(75), 9,
      sym__expression,
      sym_infix_ex,
      sym_prefix_ex,
      sym_binding,
      sym_let,
      sym_lambda,
      sym_ap,
      sym_cond,
      sym_const_bool,
  [999] = 9,
    ACTIONS(5), 1,
      sym_identifier,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_DASH,
    ACTIONS(11), 1,
      anon_sym_let,
    ACTIONS(13), 1,
      anon_sym_BSLASH,
    ACTIONS(15), 1,
      anon_sym_if,
    ACTIONS(103), 1,
      sym_const_int,
    ACTIONS(19), 2,
      anon_sym_True,
      anon_sym_False,
    STATE(66), 9,
      sym__expression,
      sym_infix_ex,
      sym_prefix_ex,
      sym_binding,
      sym_let,
      sym_lambda,
      sym_ap,
      sym_cond,
      sym_const_bool,
  [1036] = 5,
    ACTIONS(105), 1,
      sym_identifier,
    ACTIONS(109), 1,
      anon_sym_EQ,
    STATE(91), 1,
      aux_sym_binding_repeat1,
    ACTIONS(111), 3,
      anon_sym_in,
      anon_sym_then,
      anon_sym_else,
    ACTIONS(107), 6,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      aux_sym_infix_ex_token1,
      aux_sym_infix_ex_token2,
      aux_sym_infix_ex_token3,
      anon_sym_COMMA,
  [1059] = 5,
    ACTIONS(113), 1,
      anon_sym_LPAREN,
    ACTIONS(117), 1,
      aux_sym_infix_ex_token1,
    ACTIONS(119), 1,
      aux_sym_infix_ex_token2,
    ACTIONS(121), 1,
      aux_sym_infix_ex_token3,
    ACTIONS(115), 5,
      anon_sym_RPAREN,
      anon_sym_in,
      anon_sym_COMMA,
      anon_sym_then,
      anon_sym_else,
  [1079] = 1,
    ACTIONS(123), 9,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      aux_sym_infix_ex_token1,
      aux_sym_infix_ex_token2,
      aux_sym_infix_ex_token3,
      anon_sym_in,
      anon_sym_COMMA,
      anon_sym_then,
      anon_sym_else,
  [1091] = 5,
    ACTIONS(113), 1,
      anon_sym_LPAREN,
    ACTIONS(117), 1,
      aux_sym_infix_ex_token1,
    ACTIONS(119), 1,
      aux_sym_infix_ex_token2,
    ACTIONS(121), 1,
      aux_sym_infix_ex_token3,
    ACTIONS(125), 5,
      anon_sym_RPAREN,
      anon_sym_in,
      anon_sym_COMMA,
      anon_sym_then,
      anon_sym_else,
  [1111] = 4,
    ACTIONS(113), 1,
      anon_sym_LPAREN,
    ACTIONS(117), 1,
      aux_sym_infix_ex_token1,
    ACTIONS(119), 1,
      aux_sym_infix_ex_token2,
    ACTIONS(127), 6,
      anon_sym_RPAREN,
      aux_sym_infix_ex_token3,
      anon_sym_in,
      anon_sym_COMMA,
      anon_sym_then,
      anon_sym_else,
  [1129] = 1,
    ACTIONS(129), 9,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      aux_sym_infix_ex_token1,
      aux_sym_infix_ex_token2,
      aux_sym_infix_ex_token3,
      anon_sym_in,
      anon_sym_COMMA,
      anon_sym_then,
      anon_sym_else,
  [1141] = 5,
    ACTIONS(113), 1,
      anon_sym_LPAREN,
    ACTIONS(117), 1,
      aux_sym_infix_ex_token1,
    ACTIONS(119), 1,
      aux_sym_infix_ex_token2,
    ACTIONS(121), 1,
      aux_sym_infix_ex_token3,
    ACTIONS(131), 5,
      anon_sym_RPAREN,
      anon_sym_in,
      anon_sym_COMMA,
      anon_sym_then,
      anon_sym_else,
  [1161] = 5,
    ACTIONS(113), 1,
      anon_sym_LPAREN,
    ACTIONS(117), 1,
      aux_sym_infix_ex_token1,
    ACTIONS(119), 1,
      aux_sym_infix_ex_token2,
    ACTIONS(121), 1,
      aux_sym_infix_ex_token3,
    ACTIONS(133), 5,
      anon_sym_RPAREN,
      anon_sym_in,
      anon_sym_COMMA,
      anon_sym_then,
      anon_sym_else,
  [1181] = 5,
    ACTIONS(135), 1,
      sym_identifier,
    ACTIONS(137), 1,
      anon_sym_EQ,
    STATE(83), 1,
      aux_sym_binding_repeat1,
    ACTIONS(107), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    ACTIONS(111), 4,
      anon_sym_LPAREN,
      aux_sym_infix_ex_token1,
      aux_sym_infix_ex_token2,
      aux_sym_infix_ex_token3,
  [1201] = 1,
    ACTIONS(139), 9,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      aux_sym_infix_ex_token1,
      aux_sym_infix_ex_token2,
      aux_sym_infix_ex_token3,
      anon_sym_in,
      anon_sym_COMMA,
      anon_sym_then,
      anon_sym_else,
  [1213] = 5,
    ACTIONS(113), 1,
      anon_sym_LPAREN,
    ACTIONS(117), 1,
      aux_sym_infix_ex_token1,
    ACTIONS(119), 1,
      aux_sym_infix_ex_token2,
    ACTIONS(121), 1,
      aux_sym_infix_ex_token3,
    ACTIONS(141), 5,
      anon_sym_RPAREN,
      anon_sym_in,
      anon_sym_COMMA,
      anon_sym_then,
      anon_sym_else,
  [1233] = 2,
    ACTIONS(113), 1,
      anon_sym_LPAREN,
    ACTIONS(143), 8,
      anon_sym_RPAREN,
      aux_sym_infix_ex_token1,
      aux_sym_infix_ex_token2,
      aux_sym_infix_ex_token3,
      anon_sym_in,
      anon_sym_COMMA,
      anon_sym_then,
      anon_sym_else,
  [1247] = 1,
    ACTIONS(145), 9,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      aux_sym_infix_ex_token1,
      aux_sym_infix_ex_token2,
      aux_sym_infix_ex_token3,
      anon_sym_in,
      anon_sym_COMMA,
      anon_sym_then,
      anon_sym_else,
  [1259] = 3,
    ACTIONS(113), 1,
      anon_sym_LPAREN,
    ACTIONS(117), 1,
      aux_sym_infix_ex_token1,
    ACTIONS(127), 7,
      anon_sym_RPAREN,
      aux_sym_infix_ex_token2,
      aux_sym_infix_ex_token3,
      anon_sym_in,
      anon_sym_COMMA,
      anon_sym_then,
      anon_sym_else,
  [1275] = 5,
    ACTIONS(113), 1,
      anon_sym_LPAREN,
    ACTIONS(117), 1,
      aux_sym_infix_ex_token1,
    ACTIONS(119), 1,
      aux_sym_infix_ex_token2,
    ACTIONS(121), 1,
      aux_sym_infix_ex_token3,
    ACTIONS(147), 5,
      anon_sym_RPAREN,
      anon_sym_in,
      anon_sym_COMMA,
      anon_sym_then,
      anon_sym_else,
  [1295] = 2,
    ACTIONS(113), 1,
      anon_sym_LPAREN,
    ACTIONS(127), 8,
      anon_sym_RPAREN,
      aux_sym_infix_ex_token1,
      aux_sym_infix_ex_token2,
      aux_sym_infix_ex_token3,
      anon_sym_in,
      anon_sym_COMMA,
      anon_sym_then,
      anon_sym_else,
  [1309] = 7,
    ACTIONS(113), 1,
      anon_sym_LPAREN,
    ACTIONS(117), 1,
      aux_sym_infix_ex_token1,
    ACTIONS(119), 1,
      aux_sym_infix_ex_token2,
    ACTIONS(121), 1,
      aux_sym_infix_ex_token3,
    ACTIONS(149), 1,
      anon_sym_RPAREN,
    ACTIONS(151), 1,
      anon_sym_COMMA,
    STATE(92), 1,
      aux_sym__param_list_repeat1,
  [1331] = 7,
    ACTIONS(153), 1,
      ts_builtin_sym_end,
    ACTIONS(155), 1,
      anon_sym_LF,
    ACTIONS(157), 1,
      anon_sym_LPAREN,
    ACTIONS(159), 1,
      aux_sym_infix_ex_token1,
    ACTIONS(161), 1,
      aux_sym_infix_ex_token2,
    ACTIONS(163), 1,
      aux_sym_infix_ex_token3,
    STATE(84), 1,
      aux_sym_unit_repeat1,
  [1353] = 2,
    ACTIONS(145), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    ACTIONS(165), 4,
      anon_sym_LPAREN,
      aux_sym_infix_ex_token1,
      aux_sym_infix_ex_token2,
      aux_sym_infix_ex_token3,
  [1364] = 5,
    ACTIONS(157), 1,
      anon_sym_LPAREN,
    ACTIONS(159), 1,
      aux_sym_infix_ex_token1,
    ACTIONS(161), 1,
      aux_sym_infix_ex_token2,
    ACTIONS(163), 1,
      aux_sym_infix_ex_token3,
    ACTIONS(115), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [1381] = 2,
    ACTIONS(139), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    ACTIONS(167), 4,
      anon_sym_LPAREN,
      aux_sym_infix_ex_token1,
      aux_sym_infix_ex_token2,
      aux_sym_infix_ex_token3,
  [1392] = 5,
    ACTIONS(113), 1,
      anon_sym_LPAREN,
    ACTIONS(117), 1,
      aux_sym_infix_ex_token1,
    ACTIONS(119), 1,
      aux_sym_infix_ex_token2,
    ACTIONS(121), 1,
      aux_sym_infix_ex_token3,
    ACTIONS(169), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1409] = 5,
    ACTIONS(157), 1,
      anon_sym_LPAREN,
    ACTIONS(159), 1,
      aux_sym_infix_ex_token1,
    ACTIONS(161), 1,
      aux_sym_infix_ex_token2,
    ACTIONS(163), 1,
      aux_sym_infix_ex_token3,
    ACTIONS(125), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [1426] = 2,
    ACTIONS(123), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    ACTIONS(171), 4,
      anon_sym_LPAREN,
      aux_sym_infix_ex_token1,
      aux_sym_infix_ex_token2,
      aux_sym_infix_ex_token3,
  [1437] = 5,
    ACTIONS(157), 1,
      anon_sym_LPAREN,
    ACTIONS(159), 1,
      aux_sym_infix_ex_token1,
    ACTIONS(161), 1,
      aux_sym_infix_ex_token2,
    ACTIONS(163), 1,
      aux_sym_infix_ex_token3,
    ACTIONS(147), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [1454] = 5,
    ACTIONS(157), 1,
      anon_sym_LPAREN,
    ACTIONS(159), 1,
      aux_sym_infix_ex_token1,
    ACTIONS(161), 1,
      aux_sym_infix_ex_token2,
    ACTIONS(163), 1,
      aux_sym_infix_ex_token3,
    ACTIONS(173), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [1471] = 5,
    ACTIONS(157), 1,
      anon_sym_LPAREN,
    ACTIONS(159), 1,
      aux_sym_infix_ex_token1,
    ACTIONS(161), 1,
      aux_sym_infix_ex_token2,
    ACTIONS(163), 1,
      aux_sym_infix_ex_token3,
    ACTIONS(133), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [1488] = 5,
    ACTIONS(157), 1,
      anon_sym_LPAREN,
    ACTIONS(159), 1,
      aux_sym_infix_ex_token1,
    ACTIONS(161), 1,
      aux_sym_infix_ex_token2,
    ACTIONS(163), 1,
      aux_sym_infix_ex_token3,
    ACTIONS(131), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [1505] = 2,
    ACTIONS(129), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    ACTIONS(175), 4,
      anon_sym_LPAREN,
      aux_sym_infix_ex_token1,
      aux_sym_infix_ex_token2,
      aux_sym_infix_ex_token3,
  [1516] = 5,
    ACTIONS(157), 1,
      anon_sym_LPAREN,
    ACTIONS(159), 1,
      aux_sym_infix_ex_token1,
    ACTIONS(161), 1,
      aux_sym_infix_ex_token2,
    ACTIONS(163), 1,
      aux_sym_infix_ex_token3,
    ACTIONS(141), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [1533] = 3,
    ACTIONS(157), 1,
      anon_sym_LPAREN,
    ACTIONS(143), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    ACTIONS(177), 3,
      aux_sym_infix_ex_token1,
      aux_sym_infix_ex_token2,
      aux_sym_infix_ex_token3,
  [1546] = 5,
    ACTIONS(157), 1,
      anon_sym_LPAREN,
    ACTIONS(159), 1,
      aux_sym_infix_ex_token1,
    ACTIONS(161), 1,
      aux_sym_infix_ex_token2,
    ACTIONS(179), 1,
      aux_sym_infix_ex_token3,
    ACTIONS(127), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [1563] = 4,
    ACTIONS(157), 1,
      anon_sym_LPAREN,
    ACTIONS(159), 1,
      aux_sym_infix_ex_token1,
    ACTIONS(127), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    ACTIONS(179), 2,
      aux_sym_infix_ex_token2,
      aux_sym_infix_ex_token3,
  [1578] = 3,
    ACTIONS(157), 1,
      anon_sym_LPAREN,
    ACTIONS(127), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    ACTIONS(179), 3,
      aux_sym_infix_ex_token1,
      aux_sym_infix_ex_token2,
      aux_sym_infix_ex_token3,
  [1591] = 5,
    ACTIONS(113), 1,
      anon_sym_LPAREN,
    ACTIONS(117), 1,
      aux_sym_infix_ex_token1,
    ACTIONS(119), 1,
      aux_sym_infix_ex_token2,
    ACTIONS(121), 1,
      aux_sym_infix_ex_token3,
    ACTIONS(181), 1,
      anon_sym_else,
  [1607] = 5,
    ACTIONS(113), 1,
      anon_sym_LPAREN,
    ACTIONS(117), 1,
      aux_sym_infix_ex_token1,
    ACTIONS(119), 1,
      aux_sym_infix_ex_token2,
    ACTIONS(121), 1,
      aux_sym_infix_ex_token3,
    ACTIONS(183), 1,
      anon_sym_RPAREN,
  [1623] = 5,
    ACTIONS(113), 1,
      anon_sym_LPAREN,
    ACTIONS(117), 1,
      aux_sym_infix_ex_token1,
    ACTIONS(119), 1,
      aux_sym_infix_ex_token2,
    ACTIONS(121), 1,
      aux_sym_infix_ex_token3,
    ACTIONS(185), 1,
      anon_sym_then,
  [1639] = 5,
    ACTIONS(113), 1,
      anon_sym_LPAREN,
    ACTIONS(117), 1,
      aux_sym_infix_ex_token1,
    ACTIONS(119), 1,
      aux_sym_infix_ex_token2,
    ACTIONS(121), 1,
      aux_sym_infix_ex_token3,
    ACTIONS(187), 1,
      anon_sym_then,
  [1655] = 5,
    ACTIONS(113), 1,
      anon_sym_LPAREN,
    ACTIONS(117), 1,
      aux_sym_infix_ex_token1,
    ACTIONS(119), 1,
      aux_sym_infix_ex_token2,
    ACTIONS(121), 1,
      aux_sym_infix_ex_token3,
    ACTIONS(189), 1,
      anon_sym_RPAREN,
  [1671] = 5,
    ACTIONS(113), 1,
      anon_sym_LPAREN,
    ACTIONS(117), 1,
      aux_sym_infix_ex_token1,
    ACTIONS(119), 1,
      aux_sym_infix_ex_token2,
    ACTIONS(121), 1,
      aux_sym_infix_ex_token3,
    ACTIONS(191), 1,
      anon_sym_else,
  [1687] = 3,
    ACTIONS(193), 1,
      sym_identifier,
    STATE(76), 1,
      aux_sym_binding_repeat1,
    ACTIONS(196), 2,
      anon_sym_EQ,
      anon_sym_DASH_GT,
  [1698] = 3,
    ACTIONS(198), 1,
      sym_identifier,
    STATE(79), 1,
      sym_binding,
    STATE(98), 1,
      sym__binding_list,
  [1708] = 3,
    ACTIONS(169), 1,
      anon_sym_RPAREN,
    ACTIONS(200), 1,
      anon_sym_COMMA,
    STATE(78), 1,
      aux_sym__param_list_repeat1,
  [1718] = 3,
    ACTIONS(203), 1,
      anon_sym_in,
    ACTIONS(205), 1,
      anon_sym_COMMA,
    STATE(86), 1,
      aux_sym__binding_list_repeat1,
  [1728] = 3,
    ACTIONS(207), 1,
      sym_identifier,
    ACTIONS(209), 1,
      anon_sym_EQ,
    STATE(91), 1,
      aux_sym_binding_repeat1,
  [1738] = 3,
    ACTIONS(211), 1,
      sym_identifier,
    ACTIONS(213), 1,
      anon_sym_DASH_GT,
    STATE(82), 1,
      aux_sym_binding_repeat1,
  [1748] = 3,
    ACTIONS(215), 1,
      sym_identifier,
    ACTIONS(217), 1,
      anon_sym_DASH_GT,
    STATE(76), 1,
      aux_sym_binding_repeat1,
  [1758] = 3,
    ACTIONS(215), 1,
      sym_identifier,
    ACTIONS(219), 1,
      anon_sym_EQ,
    STATE(76), 1,
      aux_sym_binding_repeat1,
  [1768] = 3,
    ACTIONS(47), 1,
      ts_builtin_sym_end,
    ACTIONS(221), 1,
      anon_sym_LF,
    STATE(85), 1,
      aux_sym_unit_repeat1,
  [1778] = 3,
    ACTIONS(173), 1,
      ts_builtin_sym_end,
    ACTIONS(223), 1,
      anon_sym_LF,
    STATE(85), 1,
      aux_sym_unit_repeat1,
  [1788] = 3,
    ACTIONS(205), 1,
      anon_sym_COMMA,
    ACTIONS(226), 1,
      anon_sym_in,
    STATE(89), 1,
      aux_sym__binding_list_repeat1,
  [1798] = 3,
    ACTIONS(228), 1,
      sym_identifier,
    ACTIONS(230), 1,
      anon_sym_DASH_GT,
    STATE(90), 1,
      aux_sym_binding_repeat1,
  [1808] = 3,
    ACTIONS(198), 1,
      sym_identifier,
    STATE(79), 1,
      sym_binding,
    STATE(97), 1,
      sym__binding_list,
  [1818] = 3,
    ACTIONS(232), 1,
      anon_sym_in,
    ACTIONS(234), 1,
      anon_sym_COMMA,
    STATE(89), 1,
      aux_sym__binding_list_repeat1,
  [1828] = 3,
    ACTIONS(215), 1,
      sym_identifier,
    ACTIONS(237), 1,
      anon_sym_DASH_GT,
    STATE(76), 1,
      aux_sym_binding_repeat1,
  [1838] = 3,
    ACTIONS(215), 1,
      sym_identifier,
    ACTIONS(239), 1,
      anon_sym_EQ,
    STATE(76), 1,
      aux_sym_binding_repeat1,
  [1848] = 3,
    ACTIONS(41), 1,
      anon_sym_RPAREN,
    ACTIONS(241), 1,
      anon_sym_COMMA,
    STATE(78), 1,
      aux_sym__param_list_repeat1,
  [1858] = 1,
    ACTIONS(232), 2,
      anon_sym_in,
      anon_sym_COMMA,
  [1863] = 2,
    ACTIONS(198), 1,
      sym_identifier,
    STATE(93), 1,
      sym_binding,
  [1870] = 1,
    ACTIONS(243), 1,
      anon_sym_RPAREN,
  [1874] = 1,
    ACTIONS(245), 1,
      ts_builtin_sym_end,
  [1878] = 1,
    ACTIONS(247), 1,
      anon_sym_in,
  [1882] = 1,
    ACTIONS(249), 1,
      anon_sym_in,
  [1886] = 1,
    ACTIONS(251), 1,
      anon_sym_RPAREN,
};

static uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(8)] = 0,
  [SMALL_STATE(9)] = 37,
  [SMALL_STATE(10)] = 74,
  [SMALL_STATE(11)] = 111,
  [SMALL_STATE(12)] = 148,
  [SMALL_STATE(13)] = 185,
  [SMALL_STATE(14)] = 222,
  [SMALL_STATE(15)] = 259,
  [SMALL_STATE(16)] = 296,
  [SMALL_STATE(17)] = 333,
  [SMALL_STATE(18)] = 370,
  [SMALL_STATE(19)] = 407,
  [SMALL_STATE(20)] = 444,
  [SMALL_STATE(21)] = 481,
  [SMALL_STATE(22)] = 518,
  [SMALL_STATE(23)] = 555,
  [SMALL_STATE(24)] = 592,
  [SMALL_STATE(25)] = 629,
  [SMALL_STATE(26)] = 666,
  [SMALL_STATE(27)] = 703,
  [SMALL_STATE(28)] = 740,
  [SMALL_STATE(29)] = 777,
  [SMALL_STATE(30)] = 814,
  [SMALL_STATE(31)] = 851,
  [SMALL_STATE(32)] = 888,
  [SMALL_STATE(33)] = 925,
  [SMALL_STATE(34)] = 962,
  [SMALL_STATE(35)] = 999,
  [SMALL_STATE(36)] = 1036,
  [SMALL_STATE(37)] = 1059,
  [SMALL_STATE(38)] = 1079,
  [SMALL_STATE(39)] = 1091,
  [SMALL_STATE(40)] = 1111,
  [SMALL_STATE(41)] = 1129,
  [SMALL_STATE(42)] = 1141,
  [SMALL_STATE(43)] = 1161,
  [SMALL_STATE(44)] = 1181,
  [SMALL_STATE(45)] = 1201,
  [SMALL_STATE(46)] = 1213,
  [SMALL_STATE(47)] = 1233,
  [SMALL_STATE(48)] = 1247,
  [SMALL_STATE(49)] = 1259,
  [SMALL_STATE(50)] = 1275,
  [SMALL_STATE(51)] = 1295,
  [SMALL_STATE(52)] = 1309,
  [SMALL_STATE(53)] = 1331,
  [SMALL_STATE(54)] = 1353,
  [SMALL_STATE(55)] = 1364,
  [SMALL_STATE(56)] = 1381,
  [SMALL_STATE(57)] = 1392,
  [SMALL_STATE(58)] = 1409,
  [SMALL_STATE(59)] = 1426,
  [SMALL_STATE(60)] = 1437,
  [SMALL_STATE(61)] = 1454,
  [SMALL_STATE(62)] = 1471,
  [SMALL_STATE(63)] = 1488,
  [SMALL_STATE(64)] = 1505,
  [SMALL_STATE(65)] = 1516,
  [SMALL_STATE(66)] = 1533,
  [SMALL_STATE(67)] = 1546,
  [SMALL_STATE(68)] = 1563,
  [SMALL_STATE(69)] = 1578,
  [SMALL_STATE(70)] = 1591,
  [SMALL_STATE(71)] = 1607,
  [SMALL_STATE(72)] = 1623,
  [SMALL_STATE(73)] = 1639,
  [SMALL_STATE(74)] = 1655,
  [SMALL_STATE(75)] = 1671,
  [SMALL_STATE(76)] = 1687,
  [SMALL_STATE(77)] = 1698,
  [SMALL_STATE(78)] = 1708,
  [SMALL_STATE(79)] = 1718,
  [SMALL_STATE(80)] = 1728,
  [SMALL_STATE(81)] = 1738,
  [SMALL_STATE(82)] = 1748,
  [SMALL_STATE(83)] = 1758,
  [SMALL_STATE(84)] = 1768,
  [SMALL_STATE(85)] = 1778,
  [SMALL_STATE(86)] = 1788,
  [SMALL_STATE(87)] = 1798,
  [SMALL_STATE(88)] = 1808,
  [SMALL_STATE(89)] = 1818,
  [SMALL_STATE(90)] = 1828,
  [SMALL_STATE(91)] = 1838,
  [SMALL_STATE(92)] = 1848,
  [SMALL_STATE(93)] = 1858,
  [SMALL_STATE(94)] = 1863,
  [SMALL_STATE(95)] = 1870,
  [SMALL_STATE(96)] = 1874,
  [SMALL_STATE(97)] = 1878,
  [SMALL_STATE(98)] = 1882,
  [SMALL_STATE(99)] = 1886,
};

static TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unit, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(77),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(54),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(88),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [37] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__param_list, 2),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__param_list, 3),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unit, 2),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unit, 3),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [105] = {.entry = {.count = 1, .reusable = false}}, SHIFT(91),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression, 1),
  [109] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [111] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__expression, 1),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binding, 3, .production_id = 3),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ap, 3, .production_id = 4),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_lambda, 3, .production_id = 2),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_infix_ex, 3, .production_id = 5),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression, 3),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_lambda, 4, .production_id = 7),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binding, 4, .production_id = 8),
  [135] = {.entry = {.count = 1, .reusable = false}}, SHIFT(83),
  [137] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ap, 4, .production_id = 9),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_let, 4, .production_id = 6),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_prefix_ex, 2, .production_id = 1),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_const_bool, 1),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cond, 6, .production_id = 10),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__param_list, 1),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unit, 1),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [157] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [159] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [161] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [163] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [165] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_const_bool, 1),
  [167] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_ap, 4, .production_id = 9),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__param_list_repeat1, 2),
  [171] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_ap, 3, .production_id = 4),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_unit_repeat1, 2),
  [175] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__expression, 3),
  [177] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_prefix_ex, 2, .production_id = 1),
  [179] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_infix_ex, 3, .production_id = 5),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [193] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_binding_repeat1, 2), SHIFT_REPEAT(76),
  [196] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_binding_repeat1, 2),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [200] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__param_list_repeat1, 2), SHIFT_REPEAT(28),
  [203] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__binding_list, 1),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [207] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [213] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [223] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_unit_repeat1, 2), SHIFT_REPEAT(33),
  [226] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__binding_list, 2),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [232] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__binding_list_repeat1, 2),
  [234] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__binding_list_repeat1, 2), SHIFT_REPEAT(94),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [239] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [241] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [243] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [245] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [247] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [251] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_fang(void) {
  static TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .alias_map = ts_non_terminal_alias_map,
    .state_count = STATE_COUNT,
    .symbol_metadata = ts_symbol_metadata,
    .parse_table = (const unsigned short *)ts_parse_table,
    .small_parse_table = (const uint16_t *)ts_small_parse_table,
    .small_parse_table_map = (const uint32_t *)ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .lex_modes = ts_lex_modes,
    .symbol_names = ts_symbol_names,
    .public_symbol_map = ts_symbol_map,
    .alias_sequences = (const TSSymbol *)ts_alias_sequences,
    .field_count = FIELD_COUNT,
    .field_names = ts_field_names,
    .field_map_slices = (const TSFieldMapSlice *)ts_field_map_slices,
    .field_map_entries = (const TSFieldMapEntry *)ts_field_map_entries,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
